name: hy_guard
description: "Hy Guard - Hyper security storage for all your data"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# =======================
# Main dependencies
# =======================
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flex_color_scheme: ^8.3.0
  firebase_core: ^4.0.0
  flutter_screenutil: ^5.9.3
  loading_animation_widget: ^1.3.0
  firebase_auth: ^6.0.1
  flutter_bloc: ^9.1.1
  google_sign_in: ^7.1.1
  flutter_dotenv: ^6.0.0
  flutter_quill: ^11.4.2
  hive_ce_flutter: ^2.3.2
  awesome_snackbar_content: ^0.1.8
  share_plus: ^12.0.0
  file_picker: ^10.3.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  video_thumbnail: ^0.5.6
  pdf_image_renderer: ^1.0.1
  ellipsized_text: ^2.0.0
  auto_size_text: ^3.0.0
  octo_image: ^2.1.0
  simple_animation_progress_bar: ^1.9.2


# =======================
# Development dependencies
# =======================
dev_dependencies:
  build_runner: ^2.7.0
  hive_ce_generator: ^1.9.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# =======================
# Flutter specific config
# =======================
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
