// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:hy_guard/data/storage/models/hive_models/hive_file.dart';
import 'package:hy_guard/data/storage/models/hive_models/hive_folder.dart';
import 'package:hy_guard/data/storage/models/hive_models/hive_recent_file.dart';
import 'package:hy_guard/data/storage/models/hive_models/hive_recent_search.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveFileAdapter());
    registerAdapter(HiveFolderAdapter());
    registerAdapter(HiveRecentFileAdapter());
    registerAdapter(HiveRecentSearchAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HiveFileAdapter());
    registerAdapter(HiveFolderAdapter());
    registerAdapter(HiveRecentFileAdapter());
    registerAdapter(HiveRecentSearchAdapter());
  }
}
